---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: export-fusion-parquet
  namespace: weather
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/hostname: HOSTNAME
          containers:
            - name: exporter
              image: docker.io/library/python:3.11-slim
              imagePullPolicy: IfNotPresent
              env:
                - name: PGHOST
                  value: weather-postgres
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_DATABASE
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_PASSWORD
                - name: OUT_DIR
                  value: /var/exports
                - name: RETAIN_COUNT
                  value: "30"
              command:
                - /bin/bash
                - -c
              args:
                - |
                  set -e
                  python -m pip install --no-cache-dir psycopg2-binary pandas pyarrow
                  python /opt/export/export_fusion_parquet.py
              volumeMounts:
                - name: exports
                  mountPath: /var/exports
                - name: exporter-script
                  mountPath: /opt/export/export_fusion_parquet.py
                  subPath: export_fusion_parquet.py
          volumes:
            - name: exports
              hostPath:
                path: /media/ssd250/weather/exports
                type: DirectoryOrCreate
            - name: exporter-script
              configMap:
                name: export-fusion-parquet-script
