apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: registry
          image: docker.io/registry:2
          ports:
          - containerPort: 5000
            name: registry-cport
          volumeMounts:
          - name: registry-vol
            mountPath: /var/lib/registry          
      volumes:
        - name: registry-vol
          persistentVolumeClaim:
            claimName: local-path-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: web
spec:
  selector:
    app: docker-registry
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000       # The port exposed on nodes
      targetPort: registry-cport   # The port your app is listening on in the pods
      nodePort: 30000
