apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: weather
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    autosave_interval 30

    listener 1883
    allow_anonymous true

    log_dest stdout
