apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-postgres-pvc
  namespace: weather
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-ssd
  volumeName: weather-postgres-pv
