apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-postgres-backup
  namespace: weather
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/hostname: HOSTNAME
          containers:
            - name: backup
              image: docker.io/library/postgres:16-alpine
              imagePullPolicy: IfNotPresent
              env:
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_DATABASE
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_PASSWORD
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_PASSWORD
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  ts=$(date +%F_%H%M%S)
                  pg_dump -h weather-postgres -U "$POSTGRES_USER" "$POSTGRES_DB" > /backups/weather_${ts}.sql
                  ls -1t /backups/weather_*.sql | tail -n +8 | xargs -r rm -f
              volumeMounts:
                - name: backups
                  mountPath: /backups
          volumes:
            - name: backups
              hostPath:
                path: /media/ssd250/weather/backups
                type: DirectoryOrCreate
