apiVersion: v1
kind: Service
metadata:
  name: mqtt-nodeport
  namespace: weather
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: 31884
