apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-web
  namespace: weather
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: HOSTNAME.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-web
                port:
                  number: 80

