apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-web
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-web
  template:
    metadata:
      labels:
        app: weather-web
    spec:
      initContainers:
        - name: inbox-permissions
          image: docker.io/library/busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /var/inbox
              chown 1:1 /var/inbox
              chmod 775 /var/inbox
          volumeMounts:
            - name: inbox
              mountPath: /var/inbox
      containers:
        - name: nginx
          image: docker.io/library/nginx:1.25-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: web-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: web-app
              mountPath: /app
        - name: phpfpm
          image: docker.io/bitnami/php-fpm:8.2.7-debian-11-r4
          imagePullPolicy: IfNotPresent
          env:
            - name: PHP_POST_MAX_SIZE
              value: 256M
            - name: PHP_UPLOAD_MAX_FILESIZE
              value: 256M
            - name: DB_HOST
              value: weather-postgres.weather.svc.cluster.local
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: weather-db
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: weather-db
                  key: MYSQL_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: weather-db
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 9000
              name: fastcgi
          volumeMounts:
            - name: web-app
              mountPath: /app
            - name: inbox
              mountPath: /var/inbox
            - name: db-secret
              mountPath: /var/secret
            - name: php-config
              mountPath: /opt/bitnami/php/etc/conf.d/php-ext.ini
              subPath: php-ext.ini
      volumes:
        - name: web-config
          configMap:
            name: weather-web-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: web-app
          configMap:
            name: weather-web-config
            items:
              - key: index.php
                path: index.php
              - key: export.php
                path: export.php
              - key: ingest.php
                path: ingest.php
        - name: php-config
          configMap:
            name: weather-web-config
            items:
              - key: php-ext.ini
                path: php-ext.ini
        - name: inbox
          hostPath:
            path: /media/ssd250/weather/inbox
            type: DirectoryOrCreate
        - name: db-secret
          secret:
            secretName: weather-db
