apiVersion: v1
kind: Service
metadata:
  name: weather-postgres
  namespace: weather
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: weather-postgres
