apiVersion: v1
kind: Namespace
metadata:
  name: weather
  labels:
    name: weather
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-postgres-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  hostPath:
    path: /media/ssd250/weather/postgres
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - radxa-a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-postgres-pvc
  namespace: weather
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-ssd
  volumeName: weather-postgres-pv
---
apiVersion: v1
kind: Service
metadata:
  name: weather-postgres
  namespace: weather
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: weather-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weather-postgres
  namespace: weather
spec:
  serviceName: weather-postgres
  replicas: 1
  selector:
    matchLabels:
      app: weather-postgres
  template:
    metadata:
      labels:
        app: weather-postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:16-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: weather-db
                  key: MYSQL_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: weather-db
                  key: MYSQL_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: weather-db
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: weather-postgres-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-postgres-backup
  namespace: weather
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            kubernetes.io/hostname: radxa-a
          containers:
            - name: backup
              image: docker.io/library/postgres:16-alpine
              imagePullPolicy: IfNotPresent
              env:
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_DATABASE
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_PASSWORD
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_PASSWORD
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  ts=$(date +%F_%H%M%S)
                  pg_dump -h weather-postgres -U "$POSTGRES_USER" "$POSTGRES_DB" > /backups/weather_${ts}.sql
                  ls -1t /backups/weather_*.sql | tail -n +8 | xargs -r rm -f
              volumeMounts:
                - name: backups
                  mountPath: /backups
          volumes:
            - name: backups
              hostPath:
                path: /media/ssd250/weather/backups
                type: DirectoryOrCreate
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather-sqlite-import
  namespace: weather
spec:
  schedule: "10 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: importer
              image: docker.io/library/python:3.11-slim
              imagePullPolicy: IfNotPresent
              env:
                - name: PGHOST
                  value: weather-postgres
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_DATABASE
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_PASSWORD
                - name: INBOX_DIR
                  value: /var/inbox
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  python -m pip install --no-cache-dir psycopg2-binary
                  python /opt/sqlite/sqlite_import.py
              volumeMounts:
                - name: inbox
                  mountPath: /var/inbox
                - name: sqlite-importer-script
                  mountPath: /opt/sqlite/sqlite_import.py
                  subPath: sqlite_import.py
          volumes:
            - name: inbox
              hostPath:
                path: /media/ssd250/weather/inbox
                type: DirectoryOrCreate
            - name: sqlite-importer-script
              configMap:
                name: weather-sqlite-import-script
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: entsoe-dayahead-import
  namespace: weather
spec:
                  psql -f /opt/sql/view/create_fusion_view.sql
              volumeMounts:
                - name: fusion-view-script
                  mountPath: /opt/sql/view/create_fusion_view.sql
                  subPath: create_fusion_view.sql
                      name: entsoe-api
            - name: fusion-view-script
              configMap:
                name: create-fusion-view-script
                      key: API_KEY
                - name: ENTSOE_IN_DOMAIN
                  value: 10YFI-1--------U
                - name: ENTSOE_OUT_DOMAIN
                  value: 10YFI-1--------U
                - name: ENTSOE_MARKET_AGREEMENT
                  value: A01
                - name: ENTSOE_TZ
                  value: Europe/Helsinki
              command:
                - /bin/bash
                - -c
              args:
                - |
                  set -e
                  python -m pip install --no-cache-dir psycopg2-binary requests
                  python /opt/entsoe/entsoe_import.py
              volumeMounts:
                - name: entsoe-importer-script
                  mountPath: /opt/entsoe/entsoe_import.py
                  subPath: entsoe_import.py
          volumes:
            - name: entsoe-importer-script
              configMap:
                name: entsoe-importer-script
---
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-fusion-view
  namespace: weather
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: view-creator
              image: docker.io/library/postgres:16-alpine
              imagePullPolicy: IfNotPresent
              env:
                - name: PGHOST
                  value: weather-postgres
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_DATABASE
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_PASSWORD
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  psql -c "
                  CREATE OR REPLACE VIEW weather_fusion AS
                  SELECT 
                    e.ts,
                    e.price_eur_per_mwh,
                    e.updated_at AS price_updated_at,
                    CASE 
                      WHEN EXTRACT(MINUTE FROM e.ts) = 0 THEN f1.temperature_c
                      ELSE f1.temperature_c + (f2.temperature_c - f1.temperature_c) * (EXTRACT(MINUTE FROM e.ts) / 60.0)
                    END AS temperature_c,
                    CASE 
                      WHEN EXTRACT(MINUTE FROM e.ts) = 0 THEN f1.wind_speed_ms
                      ELSE f1.wind_speed_ms + (f2.wind_speed_ms - f1.wind_speed_ms) * (EXTRACT(MINUTE FROM e.ts) / 60.0)
                    END AS wind_speed_ms,
                    CASE 
                      WHEN EXTRACT(MINUTE FROM e.ts) = 0 THEN f1.wind_direction_deg
                      ELSE f1.wind_direction_deg + (f2.wind_direction_deg - f1.wind_direction_deg) * (EXTRACT(MINUTE FROM e.ts) / 60.0)
                    END AS wind_direction_deg,
                    CASE 
                      WHEN EXTRACT(MINUTE FROM e.ts) = 0 THEN f1.cloud_cover_pct
                      ELSE f1.cloud_cover_pct + (f2.cloud_cover_pct - f1.cloud_cover_pct) * (EXTRACT(MINUTE FROM e.ts) / 60.0)
                    END AS cloud_cover_pct,
                    CASE 
                      WHEN EXTRACT(MINUTE FROM e.ts) = 0 THEN f1.shortwave_radiation_w_m2
                      ELSE f1.shortwave_radiation_w_m2 + (f2.shortwave_radiation_w_m2 - f1.shortwave_radiation_w_m2) * (EXTRACT(MINUTE FROM e.ts) / 60.0)
                    END AS shortwave_radiation_w_m2
                  FROM entsoe_prices e
                  LEFT JOIN fmi_forecast f1 ON date_trunc('hour', e.ts) = f1.ts
                  LEFT JOIN fmi_forecast f2 ON date_trunc('hour', e.ts) + interval '1 hour' = f2.ts
                  ORDER BY e.ts;
                  "
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fmi-forecast-import
  namespace: weather
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: fmi-importer
              image: docker.io/library/python:3.11-slim
              imagePullPolicy: IfNotPresent
              env:
                - name: PGHOST
                  value: weather-postgres
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_DATABASE
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: weather-db
                      key: MYSQL_PASSWORD
                - name: FMI_LAT
                  value: "60.32128967082279"
                - name: FMI_LON
                  value: "24.87694349774082"
              command:
                - /bin/bash
                - -c
              args:
                - |
                  set -e
                  python -m pip install --no-cache-dir psycopg2-binary requests lxml
                  python /opt/fmi/fmi_forecast_import.py
              volumeMounts:
                - name: fmi-importer-script
                  mountPath: /opt/fmi/fmi_forecast_import.py
                  subPath: fmi_forecast_import.py
          volumes:
            - name: fmi-importer-script
              configMap:
                name: fmi-importer-script
---
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-web
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-web
  template:
    metadata:
      labels:
        app: weather-web
    spec:
      initContainers:
        - name: inbox-permissions
          image: docker.io/library/busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /var/inbox
              chown 1:1 /var/inbox
              chmod 775 /var/inbox
          volumeMounts:
            - name: inbox
              mountPath: /var/inbox
      containers:
        - name: nginx
          image: docker.io/library/nginx:1.25-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: web-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: web-app
              mountPath: /app
        - name: phpfpm
          image: docker.io/bitnami/php-fpm:8.2.7-debian-11-r4
          imagePullPolicy: IfNotPresent
          env:
            - name: PHP_POST_MAX_SIZE
              value: 256M
            - name: PHP_UPLOAD_MAX_FILESIZE
              value: 256M
            - name: DB_HOST
              value: weather-postgres.weather.svc.cluster.local
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: weather-db
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: weather-db
                  key: MYSQL_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: weather-db
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 9000
              name: fastcgi
          volumeMounts:
            - name: web-app
              mountPath: /app
            - name: inbox
              mountPath: /var/inbox
            - name: db-secret
              mountPath: /var/secret
            - name: php-config
              mountPath: /opt/bitnami/php/etc/conf.d/php-ext.ini
              subPath: php-ext.ini
      volumes:
        - name: web-config
          configMap:
            name: weather-web-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: web-app
          configMap:
            name: weather-web-config
            items:
              - key: index.php
                path: index.php
              - key: export.php
                path: export.php
              - key: ingest.php
                path: ingest.php
        - name: php-config
          configMap:
            name: weather-web-config
            items:
              - key: php-ext.ini
                path: php-ext.ini
        - name: inbox
          hostPath:
            path: /media/ssd250/weather/inbox
            type: DirectoryOrCreate
        - name: db-secret
          secret:
            secretName: weather-db
---
apiVersion: v1
kind: Service
metadata:
  name: weather-web
  namespace: weather
spec:
  type: ClusterIP
  selector:
    app: weather-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-web
  namespace: weather
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: radxa-a.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-web
                port:
                  number: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: weather
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    autosave_interval 30

    listener 1883
    allow_anonymous true

    log_dest stdout
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ssd
  hostPath:
    path: /media/ssd250/weather/mosquitto
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - radxa-a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: weather
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-ssd
  volumeName: mosquitto-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: /mosquitto/data
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: weather
spec:
  type: ClusterIP
  selector:
    app: mosquitto
  ports:
    - port: 1883
      targetPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-nodeport
  namespace: weather
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: 31884
